Authentik
samply/secret-sync pull request #2
Opened 2024-10-23 06:48 UTC by Martin1088

Provider and app can be created.
static flow and property is missing

2025-01-08 14:00 UTC, Threated requested changes

2025-01-09 13:28 UTC, Martin1088 commented on Cargo.toml
> +anyhow = "1.0.91"
Corrected

2025-01-09 13:28 UTC, Martin1088 commented on central/Cargo.toml
> +chrono = "0.4.39"
Corrected

2025-01-09 13:33 UTC, Martin1088 commented on .cargo/config.toml
> +AUTHENTIK_TOKEN = "54s6MbwtLexO1HKKBZsPL4cq8IQCoByDE012xWFlt1jAopiS0mgB2XE8lHOw"
Deleted. Alternative ENV directly in terminal.
    // export AUTHENTIK_TOKEN=

2025-01-09 13:35 UTC, Martin1088 commented on central/src/auth/authentik/provider.rs
> +    name: &str,
client_id set for public and private

2025-01-09 13:35 UTC, Martin1088 commented on central/src/auth/config.rs
> +}
Moved to the impl

2025-01-09 13:36 UTC, Martin1088 commented on central/src/auth/config.rs
> +}
Moved central

2025-01-09 13:37 UTC, Martin1088 commented on central/src/main.rs
> +
Forgotten debugging problem. Urls now resolved.

2025-01-09 15:09 UTC, Martin1088 commented on dev-keycloak/.env
> +AUTHENTIK_LOG_LEVEL=trace
Secrets set to „admin“

2025-01-13 12:54 UTC, Threated commented
The two new commits look good to me. I need to take a look at the full changes again then I think its ready to merge

2025-01-27 14:24 UTC, Threated requested changes

2025-01-27 14:24 UTC, Threated commented on central/src/auth/authentik/mod.rs
> +        .map(|s| s.to_string())
This can be written simpler `?` or even better by using `serde_json::Value`s indexing semantics and doing `.as_str()?.clone()` at the end.

2025-01-27 14:24 UTC, Threated commented on central/src/auth/authentik/provider.rs
> +        .and_then(|v| v.as_i64())
Same as in get_uuid

2025-01-27 14:24 UTC, Threated commented on central/src/auth/authentik/test.rs
> +}
Then delete it

2025-01-27 14:24 UTC, Threated commented on central/src/auth/authentik/test.rs
> +//#[ignore = "Requires setting up a authentik"]
Keep this ignored as well

2025-01-27 14:24 UTC, Threated commented on central/src/config.rs
> +
```suggestion
```

2025-01-28 08:42 UTC, Martin1088 commented on central/src/auth/authentik/test.rs
> +//#[ignore = "Requires setting up a authentik"]
Test optimized

2025-01-28 08:44 UTC, Martin1088 commented on central/src/auth/authentik/test.rs
> +}
Delete all fn that don’t work in tests

2025-01-28 08:47 UTC, Martin1088 commented on central/src/auth/authentik/provider.rs
> +        .and_then(|v| v.as_i64())
Changed all json gets to index for better over views

2025-01-28 08:47 UTC, Martin1088 commented on central/src/auth/authentik/mod.rs
> +        .map(|s| s.to_string())
Changed to index

2025-02-04 12:48 UTC, Threated commented on central/src/auth/authentik/test.rs
> +//#[ignore = "Requires setting up a authentik"]
This test still needs to be ignored again

2025-02-04 13:03 UTC, Martin1088 commented on central/src/auth/authentik/test.rs
> +//#[ignore = "Requires setting up a authentik"]
Test fixed

2025-02-04 14:38 UTC, merged